# TODO: don't allow parallel use?

name: Build docs for branches/tags
on: [push]
# TODO: specify which branches?
# TODO: also run on tags
env:
  # NB: We want to use "latest" for the main branch.
  VERSION: ${{ github.ref_name == github.event.repository.default_branch && 'latest' || github.ref_name }}
jobs:
  build-and-upload-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pages storage repository
        uses: actions/checkout@v4
        with:
          repository: mgeier/version-injector-nursery-pages
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Set Git user/email
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Check out pages storage repository
        uses: actions/checkout@v4
        with:
          path: version-injector
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Remove target directory
        run: |
          rm -rf pages/$VERSION
      - name: Install Sphinx et al.
        run: |
          python -m pip install sphinx insipid-sphinx-theme
      - name: Build with Sphinx
        run: |
          python -m sphinx version-injector/doc pages/$VERSION --doctree-dir $RUNNER_TEMP --write-all
          # We don't need this:
          rm pages/$VERSION/.buildinfo
      - name: Commit created files
        run: |
          git add pages/$VERSION
          git diff --cached --quiet || git commit -m "New files for $VERSION"
      - name: Install version_injector
        run: |
          python -m pip install git+https://github.com/mgeier/version-injector-nursery.git
      - name: Inject versions
        # TODO: set to "versions" for tags
        run: |
          python -m version_injector $VERSION variants
      - name: Commit modified files
        run: |
          git add pages
          # This changes when $VERSION is created for the first time:
          git add version-injector.toml
          git diff --cached --quiet || git commit -m "Modified files for $VERSION"
      - name: Push commits
        run: |
          git push
      # TODO: upload to pages
