# TODO: don't allow parallel use?

name: Build docs for branches/tags
on: [push]
# TODO: specify which branches?
# TODO: also run on tags
env:
  # NB: We want to use "latest" for the main branch.
  VERSION: ${{ github.ref_name == github.event.repository.default_branch && 'latest' || github.ref_name }}
jobs:
  build-and-upload-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pages storage repository
        uses: actions/checkout@v4
        with:
          repository: mgeier/version-injector-nursery-pages
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Check out pages storage repository
        uses: actions/checkout@v4
        with:
          path: version-injector
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Install Sphinx et al.
        run: |
          python -m pip install sphinx insipid-sphinx-theme
      - name: Build with Sphinx
        run: |
          python -m sphinx version-injector/doc pages/$VERSION
      - name: Install version_injector
        run: |
          python -m pip install git+https://github.com/mgeier/version-injector-nursery.git
      - name: Inject versions
        # TODO: set to "versions" for tags
        run: |
          python -m version_injector $VERSION variants

      # TODO: commit and push
      # TODO: upload to pages
